
name: CI

on:
  push:
    branches: [ main, feature ]
  pull_request:
    branches: [ main, feature ]
  workflow_dispatch:

jobs:
  check_datatypes:
    name: Run Python script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python .github/workflows/check_datatypes.py

  static-checks:
    name: 'Static checks'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Scony/godot-gdscript-toolkit@master
      - run: gdformat ./View/
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

#      - name: Build SampleApplication
#        run: ./gradlew --no-daemon build

      - name: exportGame
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.2/Godot_v4.1.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.2/Godot_v4.1.2-stable_export_templates.tpz
          relative_project_path: ./View/
          archive_output: true

      - name: Create Release
        uses: actions/create-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: v1.0.0
          release_name: Release 1.0.0
          body: |
           This is the first release.
          draft: false
          prerelease: false
          create_release: true
          archive_output: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build 
          path: |
            /home/runner/.local/share/godot/archives/
          retention-days: 2
